### ISSUE TITLE
Dialect names are inaccessible

### ISSUE THREAD

**Issue by macleginn** [ropensci/lingtypology#12]
Mech (mech1238) is a dialect of Bodo:
```R
> lang.gltc('mech1238')
mech1238 
      NA 
```
No dialect name -> no affiliation, no coords, etc.
\+ It would be advantageous to be able to access all data based on glottocodes.

**Comment by agricolamz** [comment]
I know... It little bit messy. It was actually my decision not to do it, but may be it is time to do it... I'll think about it.

**Comment by agricolamz** [comment]
@macleginn, now in the development version from github:

```
> lang.gltc('mech1238')
mech1238 
  "Mech" 
```

Sorry that I closed the issue without checking on February!
