### ISSUE TITLE
CLAHub Contributor License Agreement creation

### ISSUE THREAD

**Issue by agricolamz** [ropensci/lingtypology#21]
Dear @sckott,

I'd like to create a contributor license agreement on the <https://www.clahub.com/> with the following text:

```
Developer Certificate of Origin Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors. 1 Letterman Drive Suite D4700 San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Developer’s Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

(c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.
```

I can't do it since I'm not a package maintainer. Could you create it, or could you give me the maintainer role.

**Comment by sckott** [comment]
hi @agricolamz - I assume this is for people to sign before they contribute here. What is your reasoning?

**Comment by agricolamz** [comment]
Hi @sckott , I'd like to create it in advance in case some people will contribute. I really like idea of such document.

**Comment by sckott** [comment]
in settings in this repo you have Admin access, are you sure you can't do what you need to do?

**Comment by agricolamz** [comment]
It is really strange. Even having myself as a collaborate didn't have any effect. I still can't see myself be able to create an agreement. May be it should be done via rOpenSci account? The same story like with Travis?

**Comment by sckott** [comment]
should I try doing it?

**Comment by agricolamz** [comment]
If you can, it would be nice.

**Comment by sckott** [comment]
It looks like I can do it, but it asks for the text you'd want for the CLA and there's some options to check through - Are you sure you can't do it?  Maybe we can screen share soon so I can see what you see.

**Comment by agricolamz** [comment]
From now, I can do it. But first I've received the email with the approvement from Jason Morrison. Thank youǃ
