### ISSUE TITLE
Broken Appveyor webhook

### ISSUE THREAD

**Issue by maelle** [ropensci/lingtypology#27]
Hi @agricolamz, it seems that there have been quite a few failed Appveyor deliveries see https://github.com/ropensci/lingtypology/settings/hooks/12284750 

Since the builds are under your account, could you please contact Appveyor and ask them how to make it work again?

They'll probably ask for info about the last delivery:

* X-GitHub-Delivery: dfc9776c-55ab-11e8-9498-16250c26dbe7

* Time 2018-05-12 08:15:31

**Comment by maelle** [comment]
I forgot to mention that their email address is team@appveyor.com

**Comment by agricolamz** [comment]
Hi, @maelle , I don't know whether it is useful at all... May be it is better to turn it off? What do you think?

**Comment by maelle** [comment]
I'm not familiar with your package, if your package doesn't have one of the criteria listed in https://github.com/ropensci/onboarding-meta/issues/48 it might be ok to turn Appveyor CI off (deleting webhook, removing config file, removing badge) cc @sckott who was editor for the submission.

**Comment by maelle** [comment]
For the record Appveyor told me

   " If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

 

    If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account."

Maybe try that?

**Comment by agricolamz** [comment]
@maelle, I've decided to turn it off, since I've never get any profit for lingtypology from it.

**Comment by maelle** [comment]
Ok thx

**Comment by agricolamz** [comment]
Thank you, @maelle. BTW I'm citing your blogpost about r chunks naming to all my students.

**Comment by maelle** [comment]
Oh thanks! 😀 Don't tell them I don't always follow my own advice 🙈
