### ISSUE TITLE
All the tones are 0 when using phoible.feature(source = "UPSID") to get data.

### ISSUE THREAD

**Issue by phliulei** [ropensci/lingtypology#28]
```
> sessionInfo()$R.version$platform
[1] "x86_64-w64-mingw32"
> sessionInfo()$R.version$version.string
[1] "R version 3.5.0 (2018-04-23)"
> packageVersion("leaflet")
[1] ‘2.0.0’
> packageVersion("lingtypology")
[1] ‘1.0.12’
```
All the `tones` are `0` when using phoible.feature(source = "UPSID") to get data.

df_phoible <- phoible.feature(source = "UPSID")

**Comment by agricolamz** [comment]
Dear @phliulei,

it looks like there is no tone information on tones in UPSID databases, so `0` here is misleading... Have a look [here](http://web.phonetik.uni-frankfurt.de/upsid_info.html).

**Comment by agricolamz** [comment]
Dear @phliulei,

can I close this issue?
