### ISSUE TITLE
Mapping of relative frequencies for feature variants

### ISSUE THREAD

**Issue by margisk** [ropensci/lingtypology#29]
This is inspired by gabmap and probably useful mostly for dialectology.

Imagine dialect A has lexeme L_1 for the concept C, dialect B has lexeme L_2, and dialect C has a mixture of two in some proportion (also possible for phonetic realizations of a phoneme). It would be cool to be able to specify those variants in a cell like A/B/B, and then their relative frequency would be calculated and displayed by dots with varying gradients.

I can look into this and tell you if I can do it, if you are interested in adding it.

**Comment by agricolamz** [comment]
Personally, I think that it could be achieved by using categorical variable with values "X", "Y" and "both". What do you think?

**Comment by margisk** [comment]
Yes, this also came to my mind. It's probably fine, although some information is lost. This could illustrate transitional areas more vividly, but one has of course to think thoroughly if it has some application outside of dialect data (for typology).

**Comment by agricolamz** [comment]
But if it is colouring problem, I think it is also could be managed by setting appropriate colours.

**Comment by margisk** [comment]
Closing this for now, thanks for the suggestions!
