### ISSUE TITLE
blank map

### ISSUE THREAD

**Issue by IndianaTones** [ropensci/lingtypology#35]
Does anyone else have trouble with the png() option or is it on my end? My maps are completely blank. Thanks in advance!

**Comment by agricolamz** [comment]
Works fine for me. Is it the same with all kinds of fomats (e. g. .jpeg)? Is it possible "Copy to clipboard..."?

**Comment by IndianaTones** [comment]
Yes, it is with all kinds of formats. I can Copy to clipboard but the resolution isn't great.

**Comment by agricolamz** [comment]
And what kind of operation system do you have?

**Comment by agricolamz** [comment]
Actually I confused, could you describe how exactly you have tried to save it?

**Comment by IndianaTones** [comment]
OS: Windows 10 Pro
R-Studio Version 1.2.1335
Code: 
png(filename="mymap.png", width=3.5, height=5, units="in", res=300)
dev.off()
Result (blank page):
![mymap](https://user-images.githubusercontent.com/12430221/65391360-93f2a200-dd68-11e9-9fba-1f5029184c09.png)

**Comment by agricolamz** [comment]
Oh, I get it. But then it is not a problem of `lingtypology`, but the known problem of `leaflet`. As I wrote in [the manual](https://ropensci.github.io/lingtypology/lingtypology_creating_maps.html):

> If for some reasons you are not using RStudio or you want to automatically create and save a lot of maps, you can save a map to a variable and use the htmlwidgets package for saving created maps to an .html file. I would like to thank Timo Roettger for mentioning this problem.

```
m <- map.feature(c("Adyghe", "Korean"))
# install.packages("htmlwidgets")
library(htmlwidgets)
saveWidget(m, file="TYPE_FILE_PATH/m.html")
```

> There is an export button in RStudio, but for some reason it is not so easy to save a map as a .png or.jpg file using code. [Here](https://stackoverflow.com/questions/31336898/how-to-save-leaflet-in-r-map-as-png-or-jpg-file/34672309#34672309) is a possible solution.

**Comment by IndianaTones** [comment]
Yes, I saw that, but was hoping to get around it. Ok, so thank you though!!
