### ISSUE TITLE
Make examples work 

### ISSUE THREAD

**Issue by jeroen** [ropensci/lingtypology#41]
The CRAN version and pkgdown version of the vignette don't show the interactive examples:
  - https://cran.r-project.org/web/packages/lingtypology/vignettes/lingtypology_creating_maps.html
  - https://docs.ropensci.org/lingtypology/articles/lingtypology_creating_maps.html

This is the working version:
 - https://ropensci.github.io/lingtypology/lingtypology_creating_maps.html

Do we need something special to render the interactive version?

**Comment by agricolamz** [comment]
If it is possible to take everything from docs folder, then it will be good. In vignetts I set everything to `eval = FALSE`, since it didn't pass CRAN checks.

**Comment by jeroen** [comment]
Why didn't it pass CRAN checks? Can you try to precompute the vignettes as described here: https://ropensci.org/technotes/2019/12/08/precompute-vignettes/

**Comment by agricolamz** [comment]
Hi, @jeroen, sorry it take me some time... [I did it](https://docs.ropensci.org/lingtypology/articles/lingtypology_creating_maps.html). So it worked in most cases, but 
* it is not interactive
* in some cases pictures are blank. 
* current version with images is heavy (22.4Mb), so it won't pass CRAN checks
* all tutorials are unordered (but it is easy to fix)

So I'm still happy with my github pages tutorials, so I would like to return this link back.

OR

If it possible to run ropensci website from `docs` folder it would be lovely.
