### ISSUE TITLE
Warning message: There is no coordinates for languages Ben Tey Dogon

### ISSUE THREAD

**Issue by IndianaTones** [ropensci/lingtypology#42]
Apologies if this is not a LingTypology issue per se, but just noting that when I use Glottolog as the source for coordinates, sometimes I get the above warning message even though the coordinates for the language(s) in question are indeed to be found in Glottolog.

Advice is greatly appreciated :)

**Comment by agricolamz** [comment]
Hi! Yes, this is the problem of mismatch of Glottolog database and database in `lingtypology`. I'd do it this way:

1) Get your list of languages in some `df`
2) Try to create the map
3) Get notification mentioned above
4) Then create additional columns with longitude and latitude using 
```
df$lat <- lat.lang(df$language)
df$long <- long.lang(df$language)
```
5) Then add missing coordinates to the table (either saving it somewhere and using Excel/LibreOffice, or in R, using indices: `df$long[5] <- ...`)
6) Then create the map using `latitude =` and `langitude = ` arguments:
```
map.feature(language = df$language, latitude = df$lat, longitude = df$long, ...)
```

I hope it will help.

**Comment by agricolamz** [comment]
@IndianaTones, in the new version of lingtyplogy there are all missing languages and dialects.

```
map.feature("Ben Tey Dogon")
```

**Comment by IndianaTones** [comment]
Yes!  It works. Beautiful!
