### ISSUE TITLE
cldf

### ISSUE THREAD

**Issue by agricolamz** [ropensci/lingtypology#51]
https://twitter.com/xrotwang/status/1294971139198988288

**Comment by SimonGreenhill** [comment]
https://github.com/SimonGreenhill/rcldf reads cldf

**Comment by agricolamz** [comment]
Thank you, @SimonGreenhill!

**Comment by agricolamz** [comment]
@SimonGreenhill, why is it not on CRAN? I'd be happy to help... In September.

**Comment by SimonGreenhill** [comment]
yeah I know, before doing that I wanted to get some more testing done and check that it works properly on a range of datasets. Also need to figure out a good API to write CLDF, so it's been on hold for a little while.
