### ISSUE TITLE
No code look up for family level Glottolog

### ISSUE THREAD

**Issue by bambooforest** [ropensci/lingtypology#68]
Please, put the results of these functions below, if your issue is related to the technical bugs. Thank you!

<details> <summary> info about OS and package versions </summary>
```
> sessionInfo()$R.version$platform
[1] "x86_64-apple-darwin17.0"
> sessionInfo()$R.version$version.string
[1] "R version 4.0.5 (2021-03-31)"
> packageVersion("leaflet")
[1] ‘2.0.4.1’
> packageVersion("lingtypology")
[1] ‘1.1.5’
```
</details>

```
library(lingtypology)
> iso.gltc('zaza1246')
zaza1246 
      NA
> gltc.iso('zza')
zza 
 NA
```

The iso/gltc lookup (and vice versa) do not handle language family level mappings?

https://glottolog.org/resource/languoid/id/zaza1246

Not sure if this is a bug or a feature.

**Comment by agricolamz** [comment]
Hi, @bambooforest, yes, I'm aware of these: there is no glottocodes and iso for dialects and for not language levels in `lingtypology`, but this definitely should be corrected soon.

I think it will be fixed, when I remaster everything using [CLDF-dump](https://github.com/glottolog/glottolog-cldf) of glottolog.

**Comment by agricolamz** [comment]
I replaced the old version of the file with the new one, so in the development version from github I get the following (soon will be on CRAN):

```
> library(lingtypology)
> iso.gltc('zaza1246')
zaza1246 
   "zza" 
> gltc.iso('zza')
       zza 
"zaza1246" 
```
