### ISSUE TITLE
Link to tutorial

### ISSUE THREAD

**Issue by alenawitzlack** [ropensci/lingtypology#88]
Hey, is the link to the tutorial incorrect?
For a detailed tutorial see [GitHub pages](https://docs.ropensci.org/lingtypology/).
And there we get to the same page again.
Thanks!
Alena

**Comment by agricolamz** [comment]
Oh, hi @alenawitzlack! Yeah, it looks like there was a wrong link in the README.md, so the ropensci team catch it to the automatically generated documentation page. But I fixed it, thanks! The following link is correct:

<https://ropensci.github.io/lingtypology/>
